version: "3.2"

services:

  backend:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
    command: npm run dev

  users-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./mongodb/init-db-users.js:/docker-entrypoint-initdb.d/init-db-users.js:ro"
      
  nats:
    image: nats